### PR TITLE
Add some Turkish curse words

### PR DESCRIPTION
**Pull request by frontsideair**
These are specifically chosen to be non-misogynist, non-homophobic, non-ableist etc.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Awesome ! Thank you also for having that care !

Can you please just add them to the readme ?

**Comment by frontsideair** [comment]
Sure thing!

**Comment by SaraVieira** [comment]
Thank you :)

**Comment by SaraVieira** [comment]
Awesome ! Merged 🤗

**Pull request merged**
