### PR TITLE
add some Dutch ones

### PR DESCRIPTION
**Pull request by Haroenv**

### CODE REVIEW

**Comment by SaraVieira** [comment]
Yellow 👋

Can you please put the translations on the readme?

As this is a very serious project ahah

**Comment by Haroenv** [comment]
Oops, forgot to do that

**Comment by SaraVieira** [comment]
You are the best! Merged! 💯🎉

**Comment by Haroenv** [comment]
No you are

**Comment by SaraVieira** [comment]
We should have this fight in person at React Europe

**Pull request merged**
